require("core.options")
require("core.keymaps")
require("plugins.lazy")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.noice")
require("plugins.lsp")
